"""Read-only Kisan Saathi scenarios grounded in a saved, validated plan.

The baseline is never regenerated by running the pipeline here. Its ledger is
checked against current field inputs before comparison; all hypothetical product
quantities are an explicit scaling of that baseline. No weather request, model
call, event, or database write occurs on this path.
"""

from __future__ import annotations

import json
from math import isfinite
from typing import Any

from .. import ledger
from ..agents.validation_agent import validate_ledger_result
from .optimizer import estimate_cost
from .region_config import load_region_config

NUTRIENTS = ("N", "P2O5", "K2O")
YIELD_REASON = (
    "No validated model for the yield effect of these fertilizer changes is connected. "
    "A crop target or a model trained mainly on synthetic data is not a field yield forecast."
)


def _read_object(value: Any) -> dict:
    if isinstance(value, dict):
        return value
    try:
        parsed = json.loads(value)
        return parsed if isinstance(parsed, dict) else {}
    except (TypeError, ValueError):
        return {}


def _quantities(proof: dict) -> dict[str, float] | None:
    source = proof.get("how_much")
    if not isinstance(source, dict):
        return None
    quantities = {}
    for key, value in source.items():
        if not key.endswith("_kg_ha") or key.startswith("n_supplied"):
            continue
        try:
            number = float(value)
        except (TypeError, ValueError):
            return None
        if not isfinite(number) or number < 0:
            return None
        quantities[key] = number
    if not quantities and proof.get("status") != "NO_FERTILIZER_NEEDED":
        return None
    return quantities


def _supplied(quantities: dict[str, float], products: dict) -> dict[str, float]:
    supplied = dict.fromkeys(NUTRIENTS, 0.0)
    for key, quantity in quantities.items():
        composition = products[key.removesuffix("_kg_ha")]
        for nutrient, column in (("N", "n"), ("P2O5", "p2o5"), ("K2O", "k2o")):
            supplied[nutrient] += quantity * float(composition[column]) / 100
    return {key: round(value, 2) for key, value in supplied.items()}


def _side(
    quantities: dict[str, float], proof: dict, current_ledger: dict, products: dict,
    weather: dict, region_id: Any, *, hypothetical: bool,
) -> dict:
    supplied = _supplied(quantities, products)
    gap = current_ledger["gap"]
    excess = {key: round(max(0.0, supplied[key] - float(gap[key])), 2) for key in NUTRIENTS}
    shortfall = {key: round(max(0.0, float(gap[key]) - supplied[key]), 2) for key in NUTRIENTS}
    validation = validate_ledger_result(
        {**current_ledger, "plan_kg_ha": quantities},
        proof.get("soil_context"), weather, products, region_id,
    )
    tolerance = float(load_region_config(region_id)["rules"]["max_rates"]["rounding_tol_kg_ha"])
    notes = []
    if any(value > tolerance for value in excess.values()):
        validation["warnings"].append(
            "Product nutrients exceed the actionable gap (after soil and recorded application credits)."
        )
    if excess["N"] > tolerance:
        notes.append(
            "Extra N beyond the remaining gap increases the amount potentially lost through "
            "leaching or gaseous emissions; this is a directional caution, not a loss estimate."
        )
    if excess["P2O5"] > tolerance:
        notes.append(
            "Extra P2O5 beyond the remaining gap can accumulate in soil and increase runoff risk; "
            "the amount of runoff is not predicted."
        )
    if excess["K2O"] > tolerance:
        notes.append(
            "Extra K2O beyond the remaining gap adds fertilizer cost and may contribute to "
            "nutrient imbalance; no crop damage or yield effect is predicted."
        )
    if any(value > tolerance for value in shortfall.values()):
        validation["warnings"].append(
            "The product mix leaves part of the actionable nutrient gap unfilled. "
            "A yield effect cannot be inferred from this comparison."
        )
    if not notes:
        notes.append(
            "No nutrient excess above the configured rounding tolerance was calculated. "
            "This does not establish environmental safety or predict yield."
        )
    if not weather.get("snapshot") and weather.get("source") != "USER_SCENARIO":
        validation["warnings"].append("Application timing is not weather-validated.")
    cost, currency, citation = estimate_cost(quantities, region_id)
    return {
        "quantities": quantities,
        "status": "HYPOTHETICAL" if hypothetical else proof["status"],
        "confidence": "NOT_ASSESSED" if hypothetical else proof.get("confidence", "LOW"),
        "cost": cost, "costCurrency": currency, "costCitation": citation,
        "applicationWindow": (
            "No application window recommended for this hypothetical mix."
            if hypothetical else proof.get("when")
        ),
        "rainfallMm": weather.get("rainfall_mm_next_7d"),
        "nutrientsSupplied": supplied, "gap": gap, "excess": excess, "shortfall": shortfall,
        "validation": {
            "is_valid": validation["is_valid"],
            "warnings": validation["warnings"],
            "blocking_issues": validation["blocking_issues"],
        },
        "sustainabilityNotes": notes,
    }


def run_scenario(
    conn: Any, field_row: Any, *, fertilizer_delta_pct: float | None = None,
    rainfall_mm: float | None = None,
) -> dict:
    """Return a truthful comparison, or an explicit state without numeric output."""
    field = dict(field_row)
    delta = 0.0 if fertilizer_delta_pct is None else float(fertilizer_delta_pct)
    if not isfinite(delta) or not -100 <= delta <= 500:
        raise ValueError("fertilizer_delta_pct must be finite and between -100 and 500")
    if rainfall_mm is not None and (not isfinite(float(rainfall_mm)) or rainfall_mm < 0):
        raise ValueError("rainfall_mm must be finite and nonnegative")
    response = {
        "fieldId": field["field_code"],
        "crop": field.get("crop_name") or field.get("crop_code"),
        "status": "NO_DATA", "reason": None, "requiredActions": [],
        "baselineRecommendationId": None, "baselineGeneratedAt": None,
        "original": None, "simulated": None, "deltaCost": None, "deltaYield": None,
        "yieldStatus": "MODEL_UNAVAILABLE", "yieldReason": YIELD_REASON,
        "notes": [
            "Baseline: the saved recommendation, checked against the current field ledger.",
            "What-if quantities are scaled from that plan for comparison only; they are not a new recommendation.",
            "Costs use the same static price assumptions on both sides and are estimates per hectare.",
            "The comparison does not save a plan, record an application, or change this field.",
        ],
    }

    def unavailable(reason: str, status: str = "NO_DATA") -> dict:
        response.update(status=status, reason=reason, requiredActions=[
            "Confirm this field's soil report and crop stage.",
            "Record previous fertilizer applications or review any incomplete application history.",
            "Generate a new recommendation on the field dashboard, then return here.",
        ])
        return response

    # Read the newest record, including abstentions/invalidations. Never resurrect
    # an older proposed plan just because the newest result is unavailable.
    saved_row = conn.execute(
        """SELECT recommendation_id, plan_json, status, generated_at, invalidated_at
           FROM recommendations WHERE field_id = ?
           ORDER BY generated_at DESC, recommendation_id DESC LIMIT 1""",
        (field["field_id"],),
    ).fetchone()
    if not saved_row:
        return unavailable("Generate a recommendation for this field before comparing a scenario.")
    saved = dict(saved_row)
    proof = _read_object(saved["plan_json"])
    if saved["status"] not in ("PROPOSED", "NO_FERTILIZER_NEEDED") or saved["invalidated_at"]:
        return unavailable("The latest field recommendation is unavailable or needs to be regenerated.", "ABSTAIN")
    if not (proof.get("validation") or {}).get("is_valid") or proof.get("status") == "ABSTAIN":
        return unavailable("The saved plan does not carry a valid constraint check.", "ABSTAIN")
    if str(proof.get("field_id")) != str(field["field_id"]):
        return unavailable("The saved proof does not belong to this field.", "ABSTAIN")
    quantities = _quantities(proof)
    if quantities is None:
        return unavailable("The saved proof has no usable fertilizer quantities.", "ABSTAIN")
    current_ledger = ledger.run_field_ledger(conn, field_row)
    if current_ledger.get("status") == "ABSTAIN":
        return unavailable(current_ledger.get("reason") or "The current nutrient ledger abstained.", "ABSTAIN")
    saved_ledger = proof.get("ledger") or {}
    for key in ("crop", "current_stage", "recommendation_type", "required", "gap", "normalized_soil", "application_history"):
        if current_ledger.get(key) != saved_ledger.get(key):
            return unavailable("Field inputs changed since the saved plan. Generate a new recommendation.", "ABSTAIN")
    soil_row = conn.execute(
        """SELECT soil_test_id FROM soil_tests WHERE field_id = ?
           ORDER BY test_date DESC, soil_test_id DESC LIMIT 1""", (field["field_id"],),
    ).fetchone()
    if not soil_row or (proof.get("soil_context") or {}).get("soil_test_id") != soil_row["soil_test_id"]:
        return unavailable("The saved plan is not based on the latest confirmed soil test.", "ABSTAIN")
    products = ledger.get_products(conn)
    if any(key.removesuffix("_kg_ha") not in products for key in quantities):
        return unavailable("A fertilizer composition used in the saved plan is unavailable.", "ABSTAIN")

    region_id = field.get("region_id")
    weather = dict(proof.get("weather_context") or {})
    original = _side(quantities, proof, current_ledger, products, weather, region_id, hypothetical=False)
    if not original["validation"]["is_valid"]:
        return unavailable("The saved plan no longer passes the current constraints.", "ABSTAIN")
    simulated_weather = dict(weather)
    if rainfall_mm is not None:
        threshold = load_region_config(region_id)["rules"]["weather_windows"]["rainfall_mm_next_7d"]
        simulated_weather = {
            "rainfall_mm_next_7d": float(rainfall_mm),
            "heavy_rain_alert": rainfall_mm >= threshold,
            "source": "USER_SCENARIO",
            "alert_details": "Hypothetical rainfall entered by the user; not a weather forecast.",
        }
        response["notes"].append(
            f"Rainfall is a hypothetical {rainfall_mm:g} mm over seven days. "
            f"The scenario uses the configured {threshold:g} mm heavy-rain precaution; "
            "no rainfall probability or observed weather is invented."
        )
    scenario_quantities = {key: round(value * (1 + delta / 100), 2) for key, value in quantities.items()}
    simulated = _side(scenario_quantities, proof, current_ledger, products, simulated_weather, region_id, hypothetical=True)
    response.update(
        status="SIMULATION", original=original, simulated=simulated,
        baselineRecommendationId=saved["recommendation_id"], baselineGeneratedAt=str(saved["generated_at"]),
        deltaCost=(round(simulated["cost"] - original["cost"], 2)
                   if simulated["cost"] is not None and original["cost"] is not None else None),
    )
    return response
