import { CropConfig } from './types';

export const CROPS: Record<string, CropConfig> = {
  rice: {
    id: 'rice',
    name: 'Rice',
    icon: '🌾',
    has3D: true,
    sketchfabId: 'be6aa4ac9adc4f558cc789a0baed8ae3',
    sketchfabTitle: 'Rice Plant',
    currentStageDesc: 'Multiple tillers are developing, leaf area increases and nutrient demand is higher.',
    stages: ['Sowing', 'Germination', 'Seedling', 'Tillering', 'Panicle Initiation', 'Flowering', 'Maturity'],
    baselineFertilizer: 50,
    fertilizerRange: [40, 80],
    stageDurations: [7, 7, 14, 22, 20, 20, 30],
  },
  banana: {
    id: 'banana',
    name: 'Banana',
    icon: '🍌',
    has3D: true,
    sketchfabId: '5cb46e64d7fc40978c3d6798017eced1',
    sketchfabTitle: 'Banana Tree',
    currentStageDesc: 'Vegetative growth phase with rapid leaf emergence. High K and N demand for pseudo-stem development.',
    stages: ['Planting', 'Establishment', 'Vegetative', 'Shooting', 'Harvest'],
    baselineFertilizer: 100,
    fertilizerRange: [80, 120],
    stageDurations: [30, 60, 60, 60, 60],
  },
  cotton: {
    id: 'cotton',
    name: 'Cotton',
    icon: '☁️',
    has3D: true,
    sketchfabId: '6c6c90de4626417a92f846ad06e551fa',
    sketchfabTitle: 'Cotton Branch',
    currentStageDesc: 'Square formation stage. Critical period for boron and potassium application to support reproductive growth.',
    stages: ['Germination', 'Seedling', 'Squaring', 'Flowering', 'Boll Opening'],
    baselineFertilizer: 60,
    fertilizerRange: [50, 90],
    stageDurations: [14, 31, 20, 55, 30],
  },
  sugarcane: {
    id: 'sugarcane',
    name: 'Sugarcane',
    icon: '🎋',
    has3D: false,
    currentStageDesc: 'Rapid stalk elongation phase. Nutrient and water uptake is at peak; irrigation scheduling is critical.',
    stages: ['Germination', 'Tillering', 'Grand Growth', 'Ripening', 'Harvest'],
    baselineFertilizer: 120,
    fertilizerRange: [100, 150],
    stageDurations: [30, 60, 180, 65, 30],
  }
};
