"""
AgroTwin AI — Knowledge Agent
==============================
Implements doc 06_AGENTIC_RAG.md — Knowledge Agent section.

Responsibility (STRICT):
  - Accepts a structured query context (crop, region, crop_stage, nutrient, extra_query).
  - Builds a precise natural-language query from context.
  - Applies HARD metadata filters: region + crop are non-negotiable.
  - Returns a structured EvidencePack with citations.

CRITICAL SCOPE RULES (00_CONTEXT.md):
  - This agent ONLY returns TEXT EVIDENCE.
  - It NEVER generates fertilizer quantities (kg/ha, bags, etc.).
  - It NEVER invents agronomic thresholds.
  - If no relevant evidence is found: return EvidencePack with empty chunks +
    NO_EVIDENCE flag + lowered confidence. Do NOT fabricate evidence.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Optional

from backend.rag.ingestion import (
    ingest_documents,
    HybridIndex,
    ChunkStore,
    DOCS_DIR,
)


# ─────────────────────────────────────────────────────────────────────────────
# EvidencePack — the contract (doc 06_AGENTIC_RAG.md)
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class EvidenceChunk:
    text: str
    metadata: dict
    score: float
    citation: str


@dataclass
class EvidencePack:
    """
    Structured evidence package returned by the Knowledge Agent.
    NEVER contains kg/ha numbers generated by this agent.
    Text excerpts may quote source documents that contain such numbers —
    but those numbers come from the document, not from LLM inference.
    """
    query: str
    chunks: list[EvidenceChunk]
    applicability_notes: str
    confidence: str          # "HIGH" | "MEDIUM" | "LOW" | "NO_EVIDENCE"
    flags: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "query": self.query,
            "chunks": [
                {
                    "text": c.text,
                    "metadata": c.metadata,
                    "score": c.score,
                    "citation": c.citation,
                }
                for c in self.chunks
            ],
            "applicability_notes": self.applicability_notes,
            "confidence": self.confidence,
            "flags": self.flags,
        }

    def is_empty(self) -> bool:
        return len(self.chunks) == 0


# ─────────────────────────────────────────────────────────────────────────────
# Singleton index — built once, reused across requests
# ─────────────────────────────────────────────────────────────────────────────

_index: Optional[HybridIndex] = None


def _get_index() -> HybridIndex:
    global _index
    if _index is None:
        store = ingest_documents(DOCS_DIR)
        _index = HybridIndex(store)
        _index.build()
    return _index


def reset_index() -> None:
    """Force rebuild on next query (useful after adding new documents)."""
    global _index
    _index = None


# ─────────────────────────────────────────────────────────────────────────────
# Query builder
# ─────────────────────────────────────────────────────────────────────────────

def _build_query(
    crop: Optional[str],
    region: Optional[str],
    crop_stage: Optional[str],
    nutrient: Optional[str],
    extra_query: str,
) -> str:
    """
    Construct a natural language query from context.
    Mirrors the example from doc 06:
      "Recommended nitrogen application for rice at tillering stage
       in Kolhapur region on low-N soil"
    """
    parts: list[str] = []

    if nutrient:
        parts.append(f"Recommended {nutrient} application")
    else:
        parts.append("Fertilizer recommendation")

    if crop:
        parts.append(f"for {crop}")

    if crop_stage:
        parts.append(f"at {crop_stage} stage")

    if region:
        parts.append(f"in {region} region")

    if extra_query:
        parts.append(extra_query)

    return " ".join(parts)


# ─────────────────────────────────────────────────────────────────────────────
# Applicability notes builder
# ─────────────────────────────────────────────────────────────────────────────

def _assess_applicability(
    chunks: list[dict],
    required_region: Optional[str],
    required_crop: Optional[str],
) -> tuple[str, list[str]]:
    """
    Inspect returned chunks and produce a human-readable applicability note.
    Returns (notes_string, flags_list).
    """
    flags: list[str] = []

    if not chunks:
        flags.append("NO_EVIDENCE")
        return (
            "No evidence chunks returned. Recommendation can proceed only from "
            "deterministic ledger data, but RAG confidence penalty applies.",
            flags,
        )

    region_match_all = all(
        required_region and required_region.lower() in [
            r.lower() for r in chunk["metadata"].get("region", [])
        ]
        for chunk in chunks
    ) if required_region else True

    crop_match_all = all(
        required_crop and required_crop.lower() in [
            c.lower() for c in chunk["metadata"].get("crop", [])
        ]
        for chunk in chunks
    ) if required_crop else True

    if region_match_all and crop_match_all:
        note = "All chunks match required region and crop."
    elif region_match_all:
        note = "All chunks match region. Crop match is partial — verify applicability."
        flags.append("PARTIAL_CROP_MATCH")
    elif crop_match_all:
        note = "All chunks match crop. Region match is partial — verify applicability."
        flags.append("PARTIAL_REGION_MATCH")
    else:
        note = "Evidence is partially off-target. Cross-check before use."
        flags.append("PARTIAL_REGION_MATCH")
        flags.append("PARTIAL_CROP_MATCH")

    return note, flags


# ─────────────────────────────────────────────────────────────────────────────
# Confidence scorer
# ─────────────────────────────────────────────────────────────────────────────

def _compute_confidence(
    chunks: list[dict],
    flags: list[str],
    top_score: float,
) -> str:
    """
    Confidence tiers:
      HIGH   — ≥3 chunks, top score > 0.05, no mismatch flags
      MEDIUM — ≥1 chunk, no critical flags
      LOW    — chunks found but partial-match flags present
      NO_EVIDENCE — no chunks at all
    """
    if not chunks:
        return "NO_EVIDENCE"
    mismatch_flags = {"PARTIAL_REGION_MATCH", "PARTIAL_CROP_MATCH"}
    has_mismatch = bool(set(flags) & mismatch_flags)
    if len(chunks) >= 3 and top_score > 0.05 and not has_mismatch:
        return "HIGH"
    if not has_mismatch:
        return "MEDIUM"
    return "LOW"


# ─────────────────────────────────────────────────────────────────────────────
# Knowledge Agent — main entry point
# ─────────────────────────────────────────────────────────────────────────────

def retrieve_evidence(
    crop: Optional[str] = None,
    region: Optional[str] = None,
    crop_stage: Optional[str] = None,
    nutrient: Optional[str] = None,
    extra_query: str = "",
    top_k: int = 5,
) -> EvidencePack:
    """
    Main Knowledge Agent call.

    Args:
        crop:        Crop code or name (e.g. "rice", "BANANA").
        region:      Region name (e.g. "kolhapur", "jalgaon").
        crop_stage:  Growth stage (e.g. "tillering", "basal").
        nutrient:    Nutrient of interest (e.g. "N", "K2O").
        extra_query: Free-text addition to the query string.
        top_k:       Maximum evidence chunks to return.

    Returns:
        EvidencePack (never raises; degrades gracefully to NO_EVIDENCE).
    """

    # ── Normalise inputs ──────────────────────────────────────────────────────
    crop_norm      = crop.lower().strip()   if crop       else None
    region_norm    = region.lower().strip() if region     else None
    stage_norm     = crop_stage.lower().strip() if crop_stage else None
    nutrient_norm  = nutrient.upper().strip()   if nutrient   else None

    # ── Build NL query ────────────────────────────────────────────────────────
    query_text = _build_query(crop_norm, region_norm, stage_norm, nutrient_norm, extra_query)

    # ── Hard metadata filters (doc 06: MANDATORY) ─────────────────────────────
    # Only filter on what is provided; missing filters are not enforced.
    filters: dict = {}
    if region_norm:
        filters["region"] = region_norm
    if crop_norm:
        filters["crop"] = crop_norm
    if stage_norm:
        filters["crop_stage"] = stage_norm

    # ── Retrieve ──────────────────────────────────────────────────────────────
    try:
        idx = _get_index()
        raw_chunks = idx.query(query_text, top_k=top_k, filters=filters)
    except Exception as exc:
        # Graceful degradation — never crash the orchestrator
        return EvidencePack(
            query=query_text,
            chunks=[],
            applicability_notes=f"RAG retrieval error: {exc}",
            confidence="NO_EVIDENCE",
            flags=["RAG_ERROR"],
        )

    # ── If strict filters returned nothing, relax crop_stage filter ───────────
    if not raw_chunks and stage_norm:
        relaxed_filters = {k: v for k, v in filters.items() if k != "crop_stage"}
        try:
            raw_chunks = idx.query(query_text, top_k=top_k, filters=relaxed_filters)
        except Exception:
            pass

    # ── Package into EvidencePack ─────────────────────────────────────────────
    evidence_chunks = [
        EvidenceChunk(
            text=c["text"],
            metadata=c["metadata"],
            score=c["score"],
            citation=c["citation"],
        )
        for c in raw_chunks
    ]

    raw_dicts = raw_chunks  # for applicability check
    top_score = raw_dicts[0]["score"] if raw_dicts else 0.0

    notes, flags = _assess_applicability(raw_dicts, region_norm, crop_norm)
    confidence = _compute_confidence(raw_dicts, flags, top_score)

    return EvidencePack(
        query=query_text,
        chunks=evidence_chunks,
        applicability_notes=notes,
        confidence=confidence,
        flags=flags,
    )
